### ISSUE TITLE
Distingiush browser full screen from normal window full screen

### ISSUE THREAD

**Issue by slagiewka** [Aetf/kwin-maxmize-to-new-desktop#1] opened 2017-06-04 09:59 UTC
At the moment, when a browser window (Chrome in my case) is already in full screen mode and I open up a video in full screen (YouTube, Vimeo, whatever) and then close it - I loose my virtual desktop. The browser itself goes to a normal mode.

This, however, does not happen when browser is in its own full screen (F11). I guess the browser simply does not close full screen mode then.

Is there a way that we could prevent us from loosing desktop when FS player is closed?

**Comment by Aetf** [comment] 2017-06-05 02:52
Hi, thanks for report!

What version of Chrome and KDE Plasma are you using? And could you provide more clear steps about how to reproduce that? I tried on my system but I can't reproduce it. Here's all the combinations I've tried. And to me they are correct behaviors.

- Chrome is in normal mode, open video in full screen (e.g. click on the right corner for YouTube): new virtual desktop created. Then exiting either by F11 or esc removes the virtual desktop and returns to normal Chrome window.
- Chrome is in full screen mode (F11), so it's already on it's own virtual desktop. Opening video in full screen doesn't seems trigger another full screen event, and it just use the same virtual desktop as the one Chrome's already using.
  * If exit with F11, both the video and Chrome leaves full screen mode, and one virtual desktop got removed.
  * If exit by clicking on right corner, only the video leaves full screen, and Chrome remains full screen. No virtual desktop change.

**Comment by slagiewka** [comment] 2017-06-05 16:33
My scneario is a bit different.

1. Open Chrome
2. Go fullscreen - but not with F11. Use KWin's Fullscreen. You should be able to see i.e. tabs and address bar. Just no borders and the entire plasmashell is hidden, obviously.
3. You will get a new virtual desktop.
4. Open up a video in fullscreen.
5. VD will stay the same, as expected.
5. Close the video with Esc or on-screen button that closes fullscreen video.
6. VD will close and Chrome will get back to first VD - this is not expected.

Sadly, this does not happen to Firefox. It seems to be interpreting KWin's full screen event to be a regular F11 hit and turns itself into a native full screen mode.

So my question for the aforementioned behaviour is whether we could somehow see the difference between Chrome going back from fullscreen video and  actually closing the full screen mode for the window.

**Comment by Aetf** [comment] 2017-06-11 20:24
Chrome leaves KWin's fullscreen mode when full screen video exits. (You can check that Chrome now has window decoration, i.e. title bar and borders). That's why my script is triggered to remove VD, which is expected when some app leaves KWin's fullscreen. I'm not sure this is by design or a bug in Chrome, though.

I'm afraid there's nothing I can do with this. Maybe you can report an issue for Chrome about not to leave desktop full screen mode when full screen videos exit.

I'm closing this as  it's caused by Chrome not the script itself. But feel free to reopen this if you have further questions.

**Closed by Aetf** 2017-06-11 20:24 UTC
